In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

Initializing a Tensor
~~~~~~~~~~~~~~~~~~~~~

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data.size()

torch.Size([2, 2])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1345, 0.7566],
        [0.4731, 0.1166]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2676, 0.2109, 0.7195],
        [0.3300, 0.7605, 0.0325]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




Attributes of a Tensor
~~~~~~~~~~~~~~~~~

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [7]:
import torch.version

print(torch.cuda.is_available())
print(torch.__version__)


True
2.6.0+cu124


In [8]:
tensor = torch.rand(3,4, device='cuda')

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


--------------




Operations on Tensors
~~~~~~~~~~~~~~~~~

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, 
indexing, slicing), sampling and more are
comprehensively described `here <https://pytorch.org/docs/stable/torch.html>`__.

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using 
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [9]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




**Standard numpy-like indexing and slicing:**



In [ ]:
tensor = torch.rand(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.8478, 0.8026, 0.8071, 0.6150])
First column:  tensor([0.8478, 0.4439, 0.0867, 0.7453])
Last column: tensor([0.6150, 0.7933, 0.9844, 0.8883])
tensor([[0.8478, 0.0000, 0.8071, 0.6150],
        [0.4439, 0.0000, 0.4590, 0.7933],
        [0.0867, 0.0000, 0.2931, 0.9844],
        [0.7453, 0.0000, 0.2274, 0.8883]])


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,
another tensor joining op that is subtly different from ``torch.cat``.



In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.8478, 0.0000, 0.8071, 0.6150, 0.8478, 0.0000, 0.8071, 0.6150, 0.8478,
         0.0000, 0.8071, 0.6150],
        [0.4439, 0.0000, 0.4590, 0.7933, 0.4439, 0.0000, 0.4590, 0.7933, 0.4439,
         0.0000, 0.4590, 0.7933],
        [0.0867, 0.0000, 0.2931, 0.9844, 0.0867, 0.0000, 0.2931, 0.9844, 0.0867,
         0.0000, 0.2931, 0.9844],
        [0.7453, 0.0000, 0.2274, 0.8883, 0.7453, 0.0000, 0.2274, 0.8883, 0.7453,
         0.0000, 0.2274, 0.8883]])


**Arithmetic operations**



In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

In [26]:
m1 = torch.tensor([
    [1,2,1],
    [2,3,2]
])
m2 = torch.tensor([
    [1,2],
    [2,3],
    [1,2]
])

m1 @ m2


tensor([[ 6, 10],
        [10, 17]])

**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [29]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

7.191259384155273 <class 'float'>


**In-place operations**
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix. 
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [30]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.8478, 0.0000, 0.8071, 0.6150],
        [0.4439, 0.0000, 0.4590, 0.7933],
        [0.0867, 0.0000, 0.2931, 0.9844],
        [0.7453, 0.0000, 0.2274, 0.8883]]) 

tensor([[5.8478, 5.0000, 5.8071, 5.6150],
        [5.4439, 5.0000, 5.4590, 5.7933],
        [5.0867, 5.0000, 5.2931, 5.9844],
        [5.7453, 5.0000, 5.2274, 5.8883]])


<div class="alert alert-info"><h4>Note</h4><p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss
     of history. Hence, their use is discouraged.</p></div>



--------------





Bridge with NumPy
~~~~~~~~~~~~~~~~~
Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.



Tensor to NumPy array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [31]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [43]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")
tc = t.to('cuda')
tc.add_(1)
print(f"t: {t}")
print(f"n: {n}")
# t.device
print(f'tc: {tc}')
tc.device


t: tensor([22., 22., 22., 22., 22.])
n: [22. 22. 22. 22. 22.]
t: tensor([22., 22., 22., 22., 22.])
n: [22. 22. 22. 22. 22.]
tc: tensor([23., 23., 23., 23., 23.], device='cuda:0')


device(type='cuda', index=0)

NumPy array to Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [44]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [45]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
